name: Python 3.9 CI Pipeline

on:
  push:
    branches: 
      - main
jobs:
  lint-test-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      - name: Install Dependencies and Run Flake
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 
          flake8 .
    
      - name: Install and Run Safety
        env:
          SAFETY_API_KEY: ${{ secrets.SAFETY_API_KEY }}
        run: |
          pip install safety
          safety scan -r requirements.txt --ignore 55261
      
      - name: Install and Run Bandit
        run: |
          pip install bandit
          bandit -r . --exit-zero
